source "https://rubygems.org"

# TODO: The original content of this Gemfile was generated by dry-web-roda.
#       It is recommended to review the dependencies and define their version
#       requirements for gems that miss them.
gem "rake"

# Web framework
gem "dry-web-roda"
gem "dry-system"
gem "dry-web"
gem "puma"
gem "rack_csrf"

gem "rack", ">= 2.0"

# Database persistence
gem "pg"
gem "rom", "~> 5.1"
gem "rom-sql", "~> 3.1"

# Application dependencies
gem "dry-matcher"
gem "dry-monads"
gem "dry-struct"
gem "dry-types"
gem "dry-validation"
gem "dry-view"
gem "slim"

group :development, :test do
  gem "pry-byebug", platform: :mri
end

group :development do
  gem "rerun"
end

group :test do
  gem "capybara"
  gem "capybara-screenshot"
  gem "database_cleaner"
  gem "poltergeist"
  gem "rspec"
  gem "rom-factory", "~> 0.10"
end
