language: ruby
dist: trusty
sudo: false
services:
  - postgresql
cache: bundler
# install: true
# before_install:
#   - gem update --system
#   - gem install bundler
before_script:
  - psql -c 'create database sandbox_test;' -U postgres
script:
  - ./script/ci
rvm:
  - 2.4.0
  - 2.3.3
  - 2.2.6
  - jruby-9.1.6.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: jruby-9.1.6.0
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
