language: ruby
dist: trusty
sudo: false
cache: bundler
script:
  - ./script/ci
rvm:
  - 2.1
  - 2.2
  - 2.3.0
  - rbx
  - jruby-9000
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
