language: ruby
dist: trusty
services:
  - postgresql
cache: bundler
install: true
before_install:
  - gem update --system
before_script:
  - psql -c 'create database sandbox_test;' -U postgres
script:
  - ./script/ci
rvm:
  - 2.6.2
  - 2.5.5
  - 2.4.5
  - 2.3.8
  - jruby-9.2.7.0
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: jruby-9.2.7.0
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
