source "https://rubygems.org"

gem "rake"

# Web framework
gem "dry-web", ">= 0.5.0"
gem "dry-web-roda", ">= 0.4.0"
gem "puma"
gem "rack_csrf"

gem "rack", ">= 2.0"
gem "notgun"

# Database persistence
gem "pg"
gem "rom-repository"
gem "rom-sql"

# Application dependencies
gem "dry-matcher"
gem "dry-monads"
gem "dry-struct"
gem "dry-transaction"
gem "dry-types"
gem "dry-validation"
gem "dry-view"
gem "slim"

group :development, :test do
  gem "pry-byebug"
end

group :test do
  gem "capybara"
  gem "capybara-screenshot"
  gem "database_cleaner"
  gem "poltergeist"
  gem "rspec"
end
