#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

declare pwd=$PWD
declare cache="$pwd/vendor/cache"

cleanup() {
  ./script/teardown
}

bundle_package() {
  bundle package --all
  echo ""
}

# We may need something like this in future if we use github checkouts of gems
# (see `install_hanami_frameworks()` in hanami/hanami's setup script)
#
# install_from_git_checkouts() { }

install_base_gem() {
  bundle exec rake build
  local pkg=($pwd/pkg/dry-web-roda-*.gem)

  gem install $pkg > /dev/null
  mv $pkg $cache

  echo "Installed $pkg (from $(git rev-parse HEAD))"
  echo ""
}

generate_index() {
  pushd $cache > /dev/null
    gem generate_index
  popd > /dev/null
  echo ""
}

main() {
  cleanup &&
    bundle_package &&
    install_base_gem &&
    generate_index
}

main
