# this file is managed by dry-rb/devtools project

name: Sync files

on:
  repository_dispatch:
  push:
    branches:
      - "master"

jobs:
  sync-configs:
    runs-on: ubuntu-latest
    if: (github.event_name == 'repository_dispatch' && github.event.action == 'sync_configs') || github.event_name != 'repository_dispatch'
    env:
      GITHUB_LOGIN: dry-bot
      GITHUB_TOKEN: ${{ secrets.GH_PAT }}
    steps:
      - name: Checkout ${{github.repository}}
        uses: actions/checkout@v2
      - name: Checkout devtools
        uses: actions/checkout@v2
        with:
          repository: dry-rb/devtools
          path: tmp/devtools
      - name: Set up Ruby
        uses: eregon/use-ruby-action@master
        with:
          ruby-version: 2.6
      - name: Install latest bundler
        run: |
          gem install bundler
          bundle config set without 'test tools benchmarks docs'
      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3
      - name: Symlink ossy
        run: bundle binstubs ossy
      - name: Compile file templates
        run: tmp/devtools/bin/compile-templates $GITHUB_REPOSITORY
      - name: Update workflow files from devtools
        run: tmp/devtools/bin/sync-workflows
      - name: Update configuration files from devtools
        run: tmp/devtools/bin/sync-shared-files
      - name: Update changelog.yml from commit
        run: tmp/devtools/bin/update-changelog-from-commit $GITHUB_SHA
      - name: Compile CHANGELOG.md
        run: tmp/devtools/bin/compile-changelog
      - name: Setup git user
        run: |
          git config --local user.email "dry-bot@dry-rb.org"
          git config --local user.name "dry-bot"
      - name: Commit
        run: |
          rm bin/ossy
          git add -A
          git commit -m "[devtools] sync configs"
          git pull --rebase origin master
      - name: Push changes
        run: git push https://dry-bot:${{secrets.GH_PAT}}@github.com/${{github.repository}}.git master
